### ISSUE TITLE
portable shebang

### ISSUE THREAD

**Issue by magnetophon** [x42/matrixmixer.lv2#2]
Could you please change ``/bin/bash`` to ``#!/usr/bin/env bash`` everywhere?

Thanks!

**Comment by magnetophon** [comment]
Thanks!
Could you do ``genhead.sh`` too?

**Comment by x42** [comment]
Look at the linked diff, it does include genhead.sh: https://github.com/x42/matrixmixer.lv2/commit/2ad54ecb68bf6fbdfe618f983706881a40779458

**Comment by magnetophon** [comment]
Errm, not sure how I could have missed that.
Thanks, and sorry for the noise!
